### ISSUE TITLE
Prevent snapping

### ISSUE THREAD

**Issue by phanirithvij** [magicleon94/pagaview_synchronisation#1]
Hi, I like this implementation of your animated builder but I am unable to resolve the sudden snap issue.

I'm trying to implement a scrollable image on background.
Like in a home screen launcher.

An example:
In Evie launcher:
[this video](https://res.cloudinary.com/rootworld/video/upload/v1559369780/Evie)

But now Because of the snapping, it's like this:
[this video](https://res.cloudinary.com/rootworld/video/upload/v1559370092/Smarter_Launcher_F.mp4)

I tried storing the value just before the `_notifier.value` becomes zero and use it when it returns zero but it resulted in that weird transition that I've shown you in that above video.

What do you suggest can be done to make something like a scrollable wallpaper?

**Comment by phanirithvij** [comment]
This is my builder function for the AnimatedBuilder

```dart
builder: (context, _) {
    return Transform.translate(
        offset: Offset(-getOffset() * 60, 0),
        child: Container(
            decoration: BoxDecoration(
                image: DecorationImage(
                    image: AssetImage("assets/wallhaven-r276qj.png"),
                    fit: BoxFit.fitHeight,
                ),
            ),
            child: Container(
                width: MediaQuery.of(context).size.width * 10,
                child: null,
            ),
        )
    );
},
```

This is my initstate

```dart
ValueNotifier<double> _notifier;
double _prevnotifier;

@override
void initState() {
    super.initState();
    _notifier = ValueNotifier<double>(0);
    _prevnotifier = _notifier.value;

    _notifier.addListener(
        (){
            print('object ${_notifier.value}');
            if (_notifier.value != 0)
            _prevnotifier = _notifier.value;
        }
    );
}

double getOffset(){
    if (_notifier.value == 0 && _prevnotifier != null){
        return _prevnotifier;
    }
    return _notifier.value;
}
```

**Comment by magicleon94** [comment]
Hi phan, I'll take a look as soon as possible in order to help you resolving this! I ask you for a little patience since I've been busy with the flutter Hackathon and other events. I'll get back to you as soon as possible :)

**Comment by phanirithvij** [comment]
Thanks for your reply. I tried stack overflow but no one's replying.

**Comment by phanirithvij** [comment]
https://stackoverflow.com/questions/56405560/scrollable-background-image-in-flutter

**Comment by phanirithvij** [comment]
I want something just like this [https://github.com/kenreilly/flutter-parallax-nav-demo/](https://github.com/kenreilly/flutter-parallax-nav-demo/)

But that implementation is unnecessarily complicated

**Comment by magicleon94** [comment]
Hi there! I've read your code and from what I've understood, you're trying to gradually scroll an image according to the state of scrolling of the `PageView`. You get the snapping because of a misinterpretation of my example, let me explain.
My example drives an animation which the scrolling from one page to another, so my begin and end are within the scroll from just one page to another. What you need is through **the entire** `PageView`, which leads to a different adaption of my code. I'll walk you through it, but keep in mind it works if you're starting from page 0. 
I've adapted your code in these sections:
I've got rid of the `_getOffset` method, since it looked just a workaround for snapping and it's not necessary for what we're going to do.
Hence, I've modified your `AnimatedBuilder` this way:
```
AnimatedBuilder(
    animation: _notifier,
    builder: (context, _) {
      return Transform.translate(
        offset: Offset(-_notifier.value, 0), //notice the minus sign!
        child: Image.asset(
            "assets/wallhaven-r276qj.png",
            height: MediaQuery.of(context).size.height,
            fit: BoxFit.fitHeight
        ),
      );
    },
  ),
```

Now for the brainy part. The idea behind this is the following:
You have your `PageView`which, let's say, 10 pages ( I took out that value to a const variable for this).
While you scroll, you're navigating through a certain percentage of your `PageView`. Page 0 would be 0%, Page 1 would be 10%, page 2 would be 20% and so on.

In the `_onScroll` I got the "percentage of scrolling" as a number within 0 and 1. That said, I've calculated how much of the viewport that is. For example, if I've scrolled to page 1, I have 1/10 = 0.1 as fraction of `PageView` scrolled so far. I want then to scroll the image of -0.1*viewportWidth (watch the minus!). Enough talk, this is what the `_onScroll` method now looks like for me:

```
void _onScroll() {
  final double page = _pageController.page;
  final double fractionOfPages = page / _numberOfPages;
  final double viewportWidth = MediaQuery.of(context).size.width;
  final double fractionOfViewport = fractionOfPages * viewportWidth;
  widget.notifier.value = fractionOfViewport;
}
```

With this you don't need the `_prevNotifier` anymore, and you don't need `_previousPage` either, since your starting and ending point are not specific pages, but the entire sequence of them.

I'm not sure of explaining it right, so I'll try to rephrase it one last time:
In my example, you take as beginning point one page, and ending point its next page.
You need, however, to take the first page as starting point and the last page as ending point.

[This is the result video](https://streamable.com/04jl5), I hope that's what you needed. If you need further clarifications on what I did, just ask! 

And thank you for opening this, it was an interesting experiment!

I'll paste the full edited code in a separate comment, in case you need a full vision of that. I took it from your StackOverflow post!

**Comment by magicleon94** [comment]
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'PageView Scrolling',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>{
  ValueNotifier<double> _notifier;
  double _prevnotifier;


  @override
  void dispose() {
    _notifier?.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _notifier = ValueNotifier<double>(0);
    _prevnotifier = _notifier.value;

    _notifier.addListener(
            (){
          print('object ${_notifier.value}');
          if (_notifier.value != 0)
            _prevnotifier = _notifier.value;
        }
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          AnimatedBuilder(
            animation: _notifier,
            builder: (context, _) {
              return Transform.translate(
                offset: Offset(-_notifier.value, 0),
                child: Image.asset(
                    "assets/images/wallhaven-r276qj.png",
                    height: MediaQuery.of(context).size.height,
                    fit: BoxFit.fitHeight
                ),
              );
            },
          ),
          NotifyingPageView(
            notifier: _notifier,
          ),
        ],
      ),
    );
  }
}

class NotifyingPageView extends StatefulWidget {
  final ValueNotifier<double> notifier;

  const NotifyingPageView({Key key, this.notifier}) : super(key: key);

  @override
  _NotifyingPageViewState createState() => _NotifyingPageViewState();
}

class _NotifyingPageViewState extends State<NotifyingPageView> {
  PageController _pageController;
  static const int _numberOfPages = 10;

  void _onScroll() {
    final double page = _pageController.page;

    final double fractionOfPages = page / _numberOfPages;

    final double viewportWidth = MediaQuery.of(context).size.width;

    final double fractionOfViewport = fractionOfPages * viewportWidth;

    widget.notifier.value = fractionOfViewport;
  }

  @override
  void initState() {
    _pageController = PageController(
      initialPage: 0,
      viewportFraction: 0.9,
    )..addListener(_onScroll);

    super.initState();
  }

  List<Widget> _pages = List.generate(
    _numberOfPages,
        (index) {
      return Container(
        height: 10,
        alignment: Alignment.center,
        color: Colors.transparent,
        child: Text(
          "Card number $index",
          style: TextStyle(
            color: Colors.teal,
            fontWeight: FontWeight.bold,
            fontSize: 25,
          ),
        ),
      );
    },
  );

  @override
  Widget build(BuildContext context) {
    return PageView(
      children: _pages,
      controller: _pageController,
    );
  }
}
```

**Comment by magicleon94** [comment]
Let me know if you solved this, so I can mark this issue as closed :)

**Comment by phanirithvij** [comment]
Thank you very much for your time and a detailed explanation.
I've got an alternative working after I did a bit of research by using `OverflowBox` and its `alignment` property.

```dart
OverflowBox(
    // -1 to 1 is start to end
    alignment: Alignment(-1+getOffset()/5, 0),
    maxWidth: double.infinity,
    child: AspectRatio(
        aspectRatio: _aspectRatio, // get aspect ratio of image from width/height
        child: DecoratedBox(
            decoration: BoxDecoration(
                image: DecorationImage(
                    fit: BoxFit.fill,
                    image: _wallpaper, // AssetImage
                )
            )
        )
    )
)
```

And I've noticed that `_notifier.value - _previousPage` and removed the `- _previousPage` part.

And I had to use `OverflowBox` because it acted like [this](https://res.cloudinary.com/rootworld/video/upload/v1559370092/Smarter_Launcher_F.mp4) i.e. with the wallpaper being visible only in the initial viewport.

`OverflowBox` fixed it
Now it's like [this](https://res.cloudinary.com/rootworld/video/upload/v1559488216/Working_Parallax.mp4)

I'm designing an Android home screen launcher in flutter and this was a part of it.
Planning to let it be open-source and would greatly appreciate a professional flutter dev's guidance.
Once again, thank you very much for your help.

I will confirm whether the code you've posted is working as intended i.e. as a parallax background.
And I'll provide my alternative implementation if you'd like to see it.

**Comment by phanirithvij** [comment]
Oh and I forgot to mention that the video you've shared [this](https://streamable.com/04jl5) was giving me a `page not found` might be blocked by my ISP.

**Comment by magicleon94** [comment]
Well probably it is blocked, yeah, because it works from me here in Italy.
 The video was identical to yours, apart from the overflow stuff (it had white background).

By the way I'd love to see your alternative implementation, although I think I got the sense of it from your snippet! 
Feel free to contact me if you need advices and stuff, I'd be glad to help whenever and wherever I can :)

Oh and I'm going to take a look to OverflowBox, I've never used it before so... Thank you for sharing!

**Comment by magicleon94** [comment]
You can find my contacts on my profile

**Comment by phanirithvij** [comment]
I would accept the answer if you answer it over there at StackOverflow.
And I would answer my own question mentioning the alternative which I finally settled on because of the full wallpaper issue.
We can close this.
Thank you very much.

**Comment by magicleon94** [comment]
Well, my answer provides help only for the first part of your problem on SO, not the second, so that would not be a correct answer :( but thanks :) 
I'm marking the issue as solved!
